
version: '4'

services:
  db:
    container_name: python_postgres_container
    image: postgres:14.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    networks:
      - local-app-network

  server:
    depends_on:
      - db
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000

    networks:
      - local-app-network

  


networks:
  local-app-network:

volumes:
  postgres_data:
