
version: '4'

services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #   command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   networks:
  #     - local-app-network

  db:
    container_name: postgres_container
    image: postgres:14.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /postgres:/var/lib/postgresql/data
    
    
#     networks:
#       - local-app-network


# networks:
#   local-app-network:

# volumes:
#   postgres_data:
